AllCops:
  TargetRubyVersion: 2.7

SuggestExtensions: false

Style/Documentation:
  Enabled: false

Metrics/BlockLength:
  ExcludedMethods: ['describe', 'context']

Layout/LineLength:
  Max: 120

Metrics/LineLength:
  Max: 120
